number-guessing-game:
  min-number-to-guess: 1
  max-number-to-guess: 20
  max-number-of-guesses: 5

spring:
  application:
    name: number-guessing-game
  rabbitmq:
    addresses: amqp://parkster:parkster@localhost:5672
  data:
    mongodb:
      uri: mongodb://localhost/test

server:
  # Enabled graceful shutdown
  shutdown: graceful
